import { Nav } from "@/components/Nav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {" "}
      {/* <Nav /> */}
      <Suspense fallback={<h1>Loading...</h1>}>{children}</Suspense>
    </>
  );
}
